[2025-02-26T21:30:34.748+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T21:30:34.757+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-26T21:30:20.392913+00:00 [queued]>
[2025-02-26T21:30:34.762+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-26T21:30:20.392913+00:00 [queued]>
[2025-02-26T21:30:34.762+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-26T21:30:34.770+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): mapreduce> on 2025-02-26 21:30:20.392913+00:00
[2025-02-26T21:30:34.773+0000] {standard_task_runner.py:72} INFO - Started process 2828367 to run task
[2025-02-26T21:30:34.775+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'crypto', 'mapreduce', 'manual__2025-02-26T21:30:20.392913+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmp_gdunysh']
[2025-02-26T21:30:34.776+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask mapreduce
[2025-02-26T21:30:34.796+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto.mapreduce manual__2025-02-26T21:30:20.392913+00:00 [running]> on host ali-ThinkBook-14-G2-ITL
[2025-02-26T21:30:34.902+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali rahiqi' AIRFLOW_CTX_DAG_ID='crypto' AIRFLOW_CTX_TASK_ID='mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T21:30:20.392913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T21:30:20.392913+00:00'
[2025-02-26T21:30:34.902+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T21:30:34.909+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-26T21:30:34.910+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        hadoop jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar         -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json         -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26         -mapper /home/ali/Desktop/crypto/scripts/mapper.py         -reducer /home/ali/Desktop/crypto/scripts/reducer.py         -file /home/ali/Desktop/crypto/scripts/mapper.py         -file /home/ali/Desktop/crypto/scripts/reducer.py\n        ']
[2025-02-26T21:30:34.917+0000] {subprocess.py:99} INFO - Output:
[2025-02-26T21:30:35.284+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:35,284 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-26T21:30:35.771+0000] {subprocess.py:106} INFO - packageJobJar: [/home/ali/Desktop/crypto/scripts/mapper.py, /home/ali/Desktop/crypto/scripts/reducer.py, /tmp/hadoop-unjar12142921659976095717/] [] /tmp/streamjob17690767974650631144.jar tmpDir=null
[2025-02-26T21:30:35.840+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:35,840 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-26T21:30:35.925+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:35,925 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-26T21:30:36.064+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,064 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/ali/.staging/job_1740561960347_0009
[2025-02-26T21:30:36.246+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,246 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T21:30:36.276+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,276 INFO mapreduce.JobSubmitter: number of splits:2
[2025-02-26T21:30:36.383+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,382 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1740561960347_0009
[2025-02-26T21:30:36.383+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,382 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T21:30:36.491+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,491 INFO conf.Configuration: resource-types.xml not found
[2025-02-26T21:30:36.491+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,491 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
[2025-02-26T21:30:36.532+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,532 INFO impl.YarnClientImpl: Submitted application application_1740561960347_0009
[2025-02-26T21:30:36.554+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,554 INFO mapreduce.Job: The url to track the job: http://ali-ThinkBook-14-G2-ITL:8088/proxy/application_1740561960347_0009/
[2025-02-26T21:30:36.555+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:36,555 INFO mapreduce.Job: Running job: job_1740561960347_0009
[2025-02-26T21:30:39.580+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:39,580 INFO mapreduce.Job: Job job_1740561960347_0009 running in uber mode : false
[2025-02-26T21:30:39.582+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:39,581 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:39,595 INFO mapreduce.Job: Job job_1740561960347_0009 failed with state FAILED due to: Application application_1740561960347_0009 failed 2 times due to AM Container for appattempt_1740561960347_0009_000002 exited with  exitCode: 1
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - Failing this attempt.Diagnostics: [2025-02-26 21:30:38.904]Exception from container-launch.
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - Container id: container_1740561960347_0009_02_000001
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - Exit code: 1
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - 
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - [2025-02-26 21:30:38.906]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - Last 4096 bytes of prelaunch.err :
[2025-02-26T21:30:39.596+0000] {subprocess.py:106} INFO - Last 4096 bytes of stderr :
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - Error: Could not find or load main class org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - 
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - Please check whether your <HADOOP_HOME>/etc/hadoop/mapred-site.xml contains the below configuration:
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO -   <name>yarn.app.mapreduce.am.env</name>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO -   <name>mapreduce.map.env</name>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T21:30:39.597+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO -   <name>mapreduce.reduce.env</name>
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - 
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - [2025-02-26 21:30:38.906]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - Last 4096 bytes of prelaunch.err :
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - Last 4096 bytes of stderr :
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - Error: Could not find or load main class org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T21:30:39.598+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - 
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - Please check whether your <HADOOP_HOME>/etc/hadoop/mapred-site.xml contains the below configuration:
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO -   <name>yarn.app.mapreduce.am.env</name>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO -   <name>mapreduce.map.env</name>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO -   <name>mapreduce.reduce.env</name>
[2025-02-26T21:30:39.599+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T21:30:39.600+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T21:30:39.600+0000] {subprocess.py:106} INFO - 
[2025-02-26T21:30:39.600+0000] {subprocess.py:106} INFO - For more detailed output, check the application tracking page: http://ali-ThinkBook-14-G2-ITL:8088/cluster/app/application_1740561960347_0009 Then click on links to logs of each attempt.
[2025-02-26T21:30:39.600+0000] {subprocess.py:106} INFO - . Failing the application.
[2025-02-26T21:30:39.607+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:39,607 INFO mapreduce.Job: Counters: 0
[2025-02-26T21:30:39.607+0000] {subprocess.py:106} INFO - 2025-02-26 21:30:39,607 ERROR streaming.StreamJob: Job not successful!
[2025-02-26T21:30:39.607+0000] {subprocess.py:106} INFO - Streaming Command Failed!
[2025-02-26T21:30:39.944+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-26T21:30:39.949+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T21:30:39.953+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto, task_id=mapreduce, run_id=manual__2025-02-26T21:30:20.392913+00:00, execution_date=20250226T213020, start_date=20250226T213034, end_date=20250226T213039
[2025-02-26T21:30:39.976+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T21:30:39.976+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task mapreduce (Bash command failed. The command returned a non-zero exit code 1.; 2828367)
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T21:30:39.987+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-26T21:30:40.061+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T21:30:40.062+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
