[2025-02-26T15:05:25.655+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T15:05:25.668+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto.run_mapreduce_job manual__2025-02-26T15:00:05.111947+00:00 [queued]>
[2025-02-26T15:05:25.674+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto.run_mapreduce_job manual__2025-02-26T15:00:05.111947+00:00 [queued]>
[2025-02-26T15:05:25.674+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-26T15:05:25.683+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-26 15:00:05.111947+00:00
[2025-02-26T15:05:25.686+0000] {standard_task_runner.py:72} INFO - Started process 1370361 to run task
[2025-02-26T15:05:25.688+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'crypto', 'run_mapreduce_job', 'manual__2025-02-26T15:00:05.111947+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmp_mz0zeb8']
[2025-02-26T15:05:25.690+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask run_mapreduce_job
[2025-02-26T15:05:25.720+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto.run_mapreduce_job manual__2025-02-26T15:00:05.111947+00:00 [running]> on host ali-ThinkBook-14-G2-ITL
[2025-02-26T15:05:25.780+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali rahiqi' AIRFLOW_CTX_DAG_ID='crypto' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T15:00:05.111947+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T15:00:05.111947+00:00'
[2025-02-26T15:05:25.781+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T15:05:25.790+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-26T15:05:25.791+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        hadoop jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar         -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json         -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26         -mapper /home/ali/Desktop/crypto/scripts/mapper.py         -reducer /home/ali/Desktop/crypto/scripts/reducer.py         -file /home/ali/Desktop/crypto/scripts/mapper.py         -file /home/ali/Desktop/crypto/scripts/reducer.py\n        ']
[2025-02-26T15:05:25.797+0000] {subprocess.py:99} INFO - Output:
[2025-02-26T15:05:26.431+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:26,431 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-26T15:05:27.078+0000] {subprocess.py:106} INFO - packageJobJar: [/home/ali/Desktop/crypto/scripts/mapper.py, /home/ali/Desktop/crypto/scripts/reducer.py, /tmp/hadoop-unjar15214995962732209831/] [] /tmp/streamjob1357161076873309341.jar tmpDir=null
[2025-02-26T15:05:27.195+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:27,195 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-26T15:05:27.314+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:27,314 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-26T15:05:27.484+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:27,483 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/ali/.staging/job_1740561960347_0002
[2025-02-26T15:05:27.790+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:27,790 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T15:05:27.831+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:27,831 INFO mapreduce.JobSubmitter: number of splits:2
[2025-02-26T15:05:28.014+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,014 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1740561960347_0002
[2025-02-26T15:05:28.014+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,014 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T15:05:28.155+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,155 INFO conf.Configuration: resource-types.xml not found
[2025-02-26T15:05:28.155+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,155 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
[2025-02-26T15:05:28.200+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,200 INFO impl.YarnClientImpl: Submitted application application_1740561960347_0002
[2025-02-26T15:05:28.227+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,226 INFO mapreduce.Job: The url to track the job: http://ali-ThinkBook-14-G2-ITL:8088/proxy/application_1740561960347_0002/
[2025-02-26T15:05:28.228+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:28,228 INFO mapreduce.Job: Running job: job_1740561960347_0002
[2025-02-26T15:05:31.257+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:31,257 INFO mapreduce.Job: Job job_1740561960347_0002 running in uber mode : false
[2025-02-26T15:05:31.258+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:31,258 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-26T15:05:31.279+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:31,279 INFO mapreduce.Job: Job job_1740561960347_0002 failed with state FAILED due to: Application application_1740561960347_0002 failed 2 times due to AM Container for appattempt_1740561960347_0002_000002 exited with  exitCode: 1
[2025-02-26T15:05:31.280+0000] {subprocess.py:106} INFO - Failing this attempt.Diagnostics: [2025-02-26 15:05:30.674]Exception from container-launch.
[2025-02-26T15:05:31.280+0000] {subprocess.py:106} INFO - Container id: container_1740561960347_0002_02_000001
[2025-02-26T15:05:31.281+0000] {subprocess.py:106} INFO - Exit code: 1
[2025-02-26T15:05:31.281+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:05:31.281+0000] {subprocess.py:106} INFO - [2025-02-26 15:05:30.679]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
[2025-02-26T15:05:31.282+0000] {subprocess.py:106} INFO - Last 4096 bytes of prelaunch.err :
[2025-02-26T15:05:31.282+0000] {subprocess.py:106} INFO - Last 4096 bytes of stderr :
[2025-02-26T15:05:31.283+0000] {subprocess.py:106} INFO - Error: Could not find or load main class org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:05:31.283+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:05:31.283+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:05:31.284+0000] {subprocess.py:106} INFO - Please check whether your <HADOOP_HOME>/etc/hadoop/mapred-site.xml contains the below configuration:
[2025-02-26T15:05:31.284+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:05:31.284+0000] {subprocess.py:106} INFO -   <name>yarn.app.mapreduce.am.env</name>
[2025-02-26T15:05:31.285+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:05:31.285+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:05:31.285+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:05:31.286+0000] {subprocess.py:106} INFO -   <name>mapreduce.map.env</name>
[2025-02-26T15:05:31.286+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:05:31.287+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:05:31.287+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:05:31.287+0000] {subprocess.py:106} INFO -   <name>mapreduce.reduce.env</name>
[2025-02-26T15:05:31.288+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:05:31.288+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:05:31.288+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:05:31.289+0000] {subprocess.py:106} INFO - [2025-02-26 15:05:30.679]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
[2025-02-26T15:05:31.289+0000] {subprocess.py:106} INFO - Last 4096 bytes of prelaunch.err :
[2025-02-26T15:05:31.289+0000] {subprocess.py:106} INFO - Last 4096 bytes of stderr :
[2025-02-26T15:05:31.290+0000] {subprocess.py:106} INFO - Error: Could not find or load main class org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:05:31.290+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:05:31.290+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:05:31.291+0000] {subprocess.py:106} INFO - Please check whether your <HADOOP_HOME>/etc/hadoop/mapred-site.xml contains the below configuration:
[2025-02-26T15:05:31.291+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:05:31.291+0000] {subprocess.py:106} INFO -   <name>yarn.app.mapreduce.am.env</name>
[2025-02-26T15:05:31.292+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:05:31.292+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:05:31.292+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:05:31.293+0000] {subprocess.py:106} INFO -   <name>mapreduce.map.env</name>
[2025-02-26T15:05:31.293+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:05:31.293+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:05:31.294+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:05:31.294+0000] {subprocess.py:106} INFO -   <name>mapreduce.reduce.env</name>
[2025-02-26T15:05:31.294+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:05:31.295+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:05:31.295+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:05:31.295+0000] {subprocess.py:106} INFO - For more detailed output, check the application tracking page: http://ali-ThinkBook-14-G2-ITL:8088/cluster/app/application_1740561960347_0002 Then click on links to logs of each attempt.
[2025-02-26T15:05:31.296+0000] {subprocess.py:106} INFO - . Failing the application.
[2025-02-26T15:05:31.310+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:31,310 INFO mapreduce.Job: Counters: 0
[2025-02-26T15:05:31.310+0000] {subprocess.py:106} INFO - 2025-02-26 15:05:31,310 ERROR streaming.StreamJob: Job not successful!
[2025-02-26T15:05:31.311+0000] {subprocess.py:106} INFO - Streaming Command Failed!
[2025-02-26T15:05:31.689+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-26T15:05:31.701+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T15:05:31.706+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=crypto, task_id=run_mapreduce_job, run_id=manual__2025-02-26T15:00:05.111947+00:00, execution_date=20250226T150005, start_date=20250226T150525, end_date=20250226T150531
[2025-02-26T15:05:31.729+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T15:05:31.729+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 1.; 1370361)
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T15:05:31.756+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-26T15:05:31.769+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T15:05:31.770+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
