[2025-02-26T15:43:50.506+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T15:43:50.522+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-26T15:31:42.756859+00:00 [queued]>
[2025-02-26T15:43:50.528+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-26T15:31:42.756859+00:00 [queued]>
[2025-02-26T15:43:50.529+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-02-26T15:43:50.539+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): mapreduce> on 2025-02-26 15:31:42.756859+00:00
[2025-02-26T15:43:50.542+0000] {standard_task_runner.py:72} INFO - Started process 1536674 to run task
[2025-02-26T15:43:50.544+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'crypto', 'mapreduce', 'manual__2025-02-26T15:31:42.756859+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmpemioyuuj']
[2025-02-26T15:43:50.545+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask mapreduce
[2025-02-26T15:43:50.581+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto.mapreduce manual__2025-02-26T15:31:42.756859+00:00 [running]> on host ali-ThinkBook-14-G2-ITL
[2025-02-26T15:43:50.641+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali rahiqi' AIRFLOW_CTX_DAG_ID='crypto' AIRFLOW_CTX_TASK_ID='mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T15:31:42.756859+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T15:31:42.756859+00:00'
[2025-02-26T15:43:50.641+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T15:43:50.651+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-26T15:43:50.651+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        hadoop jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar         -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json         -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26         -mapper /home/ali/Desktop/crypto/scripts/mapper.py         -reducer /home/ali/Desktop/crypto/scripts/reducer.py         -file /home/ali/Desktop/crypto/scripts/mapper.py         -file /home/ali/Desktop/crypto/scripts/reducer.py\n        ']
[2025-02-26T15:43:50.658+0000] {subprocess.py:99} INFO - Output:
[2025-02-26T15:43:51.275+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:51,274 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-26T15:43:51.890+0000] {subprocess.py:106} INFO - packageJobJar: [/home/ali/Desktop/crypto/scripts/mapper.py, /home/ali/Desktop/crypto/scripts/reducer.py, /tmp/hadoop-unjar9724997113288189398/] [] /tmp/streamjob13103835404513962037.jar tmpDir=null
[2025-02-26T15:43:51.982+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:51,982 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-26T15:43:52.114+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:52,114 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-26T15:43:52.301+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:52,301 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/ali/.staging/job_1740561960347_0006
[2025-02-26T15:43:52.606+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:52,606 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T15:43:52.646+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:52,646 INFO mapreduce.JobSubmitter: number of splits:2
[2025-02-26T15:43:53.219+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,218 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1740561960347_0006
[2025-02-26T15:43:53.219+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,219 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T15:43:53.438+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,437 INFO conf.Configuration: resource-types.xml not found
[2025-02-26T15:43:53.438+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,438 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
[2025-02-26T15:43:53.502+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,501 INFO impl.YarnClientImpl: Submitted application application_1740561960347_0006
[2025-02-26T15:43:53.541+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,541 INFO mapreduce.Job: The url to track the job: http://ali-ThinkBook-14-G2-ITL:8088/proxy/application_1740561960347_0006/
[2025-02-26T15:43:53.543+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:53,543 INFO mapreduce.Job: Running job: job_1740561960347_0006
[2025-02-26T15:43:56.568+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:56,568 INFO mapreduce.Job: Job job_1740561960347_0006 running in uber mode : false
[2025-02-26T15:43:56.570+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:56,570 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-26T15:43:56.589+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:56,589 INFO mapreduce.Job: Job job_1740561960347_0006 failed with state FAILED due to: Application application_1740561960347_0006 failed 2 times due to AM Container for appattempt_1740561960347_0006_000002 exited with  exitCode: 1
[2025-02-26T15:43:56.590+0000] {subprocess.py:106} INFO - Failing this attempt.Diagnostics: [2025-02-26 15:43:55.924]Exception from container-launch.
[2025-02-26T15:43:56.591+0000] {subprocess.py:106} INFO - Container id: container_1740561960347_0006_02_000001
[2025-02-26T15:43:56.591+0000] {subprocess.py:106} INFO - Exit code: 1
[2025-02-26T15:43:56.592+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:43:56.592+0000] {subprocess.py:106} INFO - [2025-02-26 15:43:55.926]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
[2025-02-26T15:43:56.592+0000] {subprocess.py:106} INFO - Last 4096 bytes of prelaunch.err :
[2025-02-26T15:43:56.593+0000] {subprocess.py:106} INFO - Last 4096 bytes of stderr :
[2025-02-26T15:43:56.593+0000] {subprocess.py:106} INFO - Error: Could not find or load main class org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:43:56.593+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:43:56.593+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:43:56.594+0000] {subprocess.py:106} INFO - Please check whether your <HADOOP_HOME>/etc/hadoop/mapred-site.xml contains the below configuration:
[2025-02-26T15:43:56.594+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:43:56.594+0000] {subprocess.py:106} INFO -   <name>yarn.app.mapreduce.am.env</name>
[2025-02-26T15:43:56.594+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:43:56.595+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:43:56.595+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:43:56.595+0000] {subprocess.py:106} INFO -   <name>mapreduce.map.env</name>
[2025-02-26T15:43:56.595+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:43:56.595+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:43:56.596+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:43:56.596+0000] {subprocess.py:106} INFO -   <name>mapreduce.reduce.env</name>
[2025-02-26T15:43:56.596+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:43:56.596+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:43:56.597+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:43:56.597+0000] {subprocess.py:106} INFO - [2025-02-26 15:43:55.927]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
[2025-02-26T15:43:56.597+0000] {subprocess.py:106} INFO - Last 4096 bytes of prelaunch.err :
[2025-02-26T15:43:56.598+0000] {subprocess.py:106} INFO - Last 4096 bytes of stderr :
[2025-02-26T15:43:56.598+0000] {subprocess.py:106} INFO - Error: Could not find or load main class org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:43:56.598+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.v2.app.MRAppMaster
[2025-02-26T15:43:56.598+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:43:56.598+0000] {subprocess.py:106} INFO - Please check whether your <HADOOP_HOME>/etc/hadoop/mapred-site.xml contains the below configuration:
[2025-02-26T15:43:56.599+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:43:56.599+0000] {subprocess.py:106} INFO -   <name>yarn.app.mapreduce.am.env</name>
[2025-02-26T15:43:56.599+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:43:56.599+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:43:56.599+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:43:56.600+0000] {subprocess.py:106} INFO -   <name>mapreduce.map.env</name>
[2025-02-26T15:43:56.600+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:43:56.600+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:43:56.600+0000] {subprocess.py:106} INFO - <property>
[2025-02-26T15:43:56.601+0000] {subprocess.py:106} INFO -   <name>mapreduce.reduce.env</name>
[2025-02-26T15:43:56.601+0000] {subprocess.py:106} INFO -   <value>HADOOP_MAPRED_HOME=${full path of your hadoop distribution directory}</value>
[2025-02-26T15:43:56.601+0000] {subprocess.py:106} INFO - </property>
[2025-02-26T15:43:56.601+0000] {subprocess.py:106} INFO - 
[2025-02-26T15:43:56.601+0000] {subprocess.py:106} INFO - For more detailed output, check the application tracking page: http://ali-ThinkBook-14-G2-ITL:8088/cluster/app/application_1740561960347_0006 Then click on links to logs of each attempt.
[2025-02-26T15:43:56.602+0000] {subprocess.py:106} INFO - . Failing the application.
[2025-02-26T15:43:56.620+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:56,620 INFO mapreduce.Job: Counters: 0
[2025-02-26T15:43:56.621+0000] {subprocess.py:106} INFO - 2025-02-26 15:43:56,620 ERROR streaming.StreamJob: Job not successful!
[2025-02-26T15:43:56.621+0000] {subprocess.py:106} INFO - Streaming Command Failed!
[2025-02-26T15:43:56.995+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-26T15:43:57.006+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T15:43:57.011+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=crypto, task_id=mapreduce, run_id=manual__2025-02-26T15:31:42.756859+00:00, execution_date=20250226T153142, start_date=20250226T154350, end_date=20250226T154357
[2025-02-26T15:43:57.051+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T15:43:57.052+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task mapreduce (Bash command failed. The command returned a non-zero exit code 1.; 1536674)
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T15:43:57.072+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-26T15:43:57.085+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T15:43:57.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
